### Numpy basics 

In [1]:
import numpy as np

Crea un array de 10 ceros.

In [2]:
zero_array = np.zeros(10)
zero_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Crea un array de 10 unos.

In [3]:
one_array = np.ones(10)
one_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Crea un array de enteros del 10 al 49.

In [4]:
int_array = np.arange(10, 50)
int_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Invierte el array del ejercicio anterior.

In [5]:
inv_int_array = int_array[::-1]
inv_int_array

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

Crea una matriz de 3x3 con valores del 0 al 8.

In [6]:

mat_0_8 = np.arange(9).reshape(3, 3)
mat_0_8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Crea un array de 3x3 con valores aleatorios y encuentra sus propiedades.

In [7]:
mat_random = np.random.random((3, 3))
mat_random

array([[0.70475003, 0.99605581, 0.86734637],
       [0.58595254, 0.31768468, 0.6452009 ],
       [0.9327225 , 0.82374438, 0.08301581]])

In [8]:
# Forma
mat_random.shape

(3, 3)

In [9]:
# Número de dimensiones
mat_random.ndim

2

In [10]:
# Tamaño
mat_random.size

9

In [11]:
# Tipo de datos
mat_random.dtype

dtype('float64')

Crea dos arrays de 3x3 y realiza operaciones aritméticas básicas 

In [12]:
mat_random_2 = np.random.random((3, 3))
mat_random_2

array([[0.39746155, 0.49114787, 0.78738901],
       [0.07120038, 0.63371338, 0.79753365],
       [0.81857949, 0.17560311, 0.07427026]])

In [13]:
add = np.add(mat_random, mat_random_2)
add 

array([[1.10221157, 1.48720368, 1.65473538],
       [0.65715292, 0.95139806, 1.44273455],
       [1.75130199, 0.99934749, 0.15728607]])

In [14]:
subtract = np.subtract(mat_random, mat_random_2)
subtract 

array([[ 0.30728848,  0.50490794,  0.07995736],
       [ 0.51475216, -0.3160287 , -0.15233276],
       [ 0.114143  ,  0.64814128,  0.00874556]])

In [15]:
multiply = np.multiply(mat_random, mat_random_2)
multiply 

array([[0.28011104, 0.48921069, 0.682939  ],
       [0.04172004, 0.20132103, 0.51456943],
       [0.76350751, 0.14465207, 0.00616561]])

In [16]:
divide = np.divide(mat_random, mat_random_2)
divide 

array([[1.77312756, 2.02801614, 1.10154746],
       [8.22962678, 0.50130657, 0.8089952 ],
       [1.13944034, 4.69094426, 1.11775312]])

Calcula el producto punto de dos arrays 3x3

In [17]:
dot = np.dot(mat_random, mat_random_2)
print(dot) 

[[1.06102254 1.12965909 1.4137185 ]
 [0.7836611  0.60240966 0.76265606]
 [0.49732728 0.99470034 1.39754492]]


Crea un array de 5x5 con valores aleatorios y encuentra su suma, media, desviación estándar y varianza.

In [18]:
mat_random_3 = np.random.random((5, 5))
mat_random_3

array([[0.41105355, 0.12267913, 0.14095369, 0.12009534, 0.21699539],
       [0.4098011 , 0.08257852, 0.74079937, 0.852066  , 0.75806209],
       [0.83305096, 0.68475191, 0.86856574, 0.00543954, 0.95599173],
       [0.95639569, 0.90669952, 0.87426021, 0.94497262, 0.41857573],
       [0.11121549, 0.40354197, 0.7390632 , 0.17664438, 0.08904115]])

In [19]:
# Suma
np.sum(mat_random_3)

12.8232940041859

In [20]:
# Media
np.mean(mat_random_3)

0.512931760167436

In [21]:
# Desviación estándar
np.std(mat_random_3)

0.3390112403627604

In [22]:
# Varianza
np.var(mat_random_3)

0.11492862109229733

Aplica las funciones seno, coseno y logaritmo a un array de 10 elementos aleatorios.

In [23]:
random_array = np.random.random(10)
random_array

array([0.2878771 , 0.03998401, 0.11688536, 0.53971972, 0.69313761,
       0.72011707, 0.63889384, 0.54057216, 0.78026081, 0.0543698 ])

In [24]:
np.sin(random_array)

array([0.28391733, 0.03997336, 0.11661939, 0.51389557, 0.63895392,
       0.65947268, 0.59630783, 0.51462665, 0.70346481, 0.05434302])

In [25]:
np.cos(random_array)

array([0.95884876, 0.99920075, 0.99317668, 0.85785275, 0.76924501,
       0.75172853, 0.80275586, 0.85741438, 0.71073009, 0.99852233])

In [26]:
np.log(random_array)

array([-1.24522163, -3.21927563, -2.14656165, -0.61670531, -0.36652672,
       -0.32834148, -0.44801698, -0.61512715, -0.24812704, -2.91194635])

### Numpy data analysis

Ejercicio: Genera un dataset sintético que simule datos de ventas. Crea un array de 100x4 donde cada fila represente una transacción con las siguientes columnas: ID del producto, Cantidad vendida, Precio unitario, y Fecha de venta

In [27]:
# Genera un array con IDs de productos aleatorios.

product_id = np.random.randint(1, 10000, size = 100)
product_id 

array([9323, 7809, 8560, 1552, 7298, 7189, 2104,  680, 3617, 9546, 8970,
       3123, 5979,  860, 2278, 8144,  215,  654, 7100, 8553, 3344, 3666,
       1573, 8802, 7343, 6522, 5519, 5089, 5140, 7392,  198, 8301, 6457,
       6176,   90, 2336, 7385, 8984, 5061, 8667, 2788, 5674,  721, 8280,
       3667,   89, 1189, 5007, 1328, 3057, 3488, 5131, 7938, 4916,  655,
       8807, 1384, 2782, 5524, 2376, 2627, 2351, 1030, 1113, 3060, 6254,
       2504,  856, 7052,  595,  274, 3037, 2077, 8252, 5916, 4651, 1018,
       6130, 9043, 8266, 5243,  915, 3422,  776, 5808, 8380, 4060, 9883,
       1631,  689, 8112, 7886, 7495, 2535, 7292, 7115, 5935, 8440, 5561,
       6533])

In [28]:
# Genera un array con cantidades vendidas aleatorias.

sale = np.random.randint(1, 500, size = 100)
sale 

array([229, 270, 429, 361, 325, 212, 165, 359, 211, 426, 464, 340, 158,
       241, 451, 228, 178, 284, 475, 222, 252, 338, 434, 472, 171, 291,
       371,  90,  14, 280, 341, 195,   1, 138, 342, 200,  29,   6, 463,
       294, 356, 233, 407,  12, 102,  78,  97, 258, 442, 290, 272,  48,
       440,  22, 326, 137, 285, 100, 103,  97,   5, 437, 140, 458, 440,
       139, 115, 292, 284, 391, 125,  33,  40, 150,  44, 399,  65, 407,
       361,  31, 284, 425,  51,  65, 362, 422, 139, 479, 359, 296, 395,
        51, 357,  72, 106, 118,  78,  21, 298,  26])

In [29]:
# Genera un array con precios unitarios aleatorios.

unit_price = np.random.randint(1, 500, size = 100)
unit_price 

array([295, 468, 368, 312, 400, 159, 258, 467, 283, 219, 199, 482, 424,
       266, 441, 240, 300,  23, 116, 489, 487, 270,  25, 242, 109, 229,
       460, 177, 344, 377, 371, 496,  78, 289, 424, 139,  24,  95, 396,
       175,  75, 212, 209, 236, 478,  31, 298, 236,  44, 476, 112, 409,
       263,  70, 412,  15, 215, 151, 408, 221, 372,  45, 108, 144, 187,
       356,  28, 309, 189, 350, 161, 290, 235,   9, 145, 120, 112,  42,
        73, 186, 458,  87, 333,  62,  79, 220, 449, 217, 407,  96, 296,
       428, 248, 125, 278,  14,  39, 447,  37, 445])

In [30]:
# Genera un array con fechas aleatorias

import pandas as pd

date = np.random.choice(pd.date_range('01/01/2022','06/08/2024'), size= 100)
date 

array(['2023-05-05T00:00:00.000000000', '2024-04-11T00:00:00.000000000',
       '2024-05-01T00:00:00.000000000', '2022-01-20T00:00:00.000000000',
       '2022-10-12T00:00:00.000000000', '2022-04-12T00:00:00.000000000',
       '2024-01-25T00:00:00.000000000', '2024-05-15T00:00:00.000000000',
       '2023-06-01T00:00:00.000000000', '2022-08-18T00:00:00.000000000',
       '2024-03-22T00:00:00.000000000', '2022-05-07T00:00:00.000000000',
       '2023-03-12T00:00:00.000000000', '2023-02-21T00:00:00.000000000',
       '2023-03-30T00:00:00.000000000', '2022-07-09T00:00:00.000000000',
       '2022-05-25T00:00:00.000000000', '2023-07-14T00:00:00.000000000',
       '2023-07-26T00:00:00.000000000', '2023-12-06T00:00:00.000000000',
       '2024-04-13T00:00:00.000000000', '2023-08-08T00:00:00.000000000',
       '2022-06-14T00:00:00.000000000', '2024-01-17T00:00:00.000000000',
       '2023-01-14T00:00:00.000000000', '2023-11-05T00:00:00.000000000',
       '2023-10-13T00:00:00.000000000', '2023-08-09

In [31]:
# Cambio el datadtype de los datos para que sean compatibles

product_id = np.array(product_id, dtype=str)
sale = np.array(sale, dtype=str)
unit_price = np.array(unit_price, dtype=str)
date = np.array(date, dtype=str)

In [32]:
# Combina estos arrays en una única matriz.

dataset_sale = np.column_stack((product_id, sale, unit_price, date))
df = pd.DataFrame(dataset_sale, columns=['Product_id', 'Sale', 'Unit_price', 'Date'])
df 

Product_id Sale Unit_price                           Date
0        9323  229        295  2023-05-05T00:00:00.000000000
1        7809  270        468  2024-04-11T00:00:00.000000000
2        8560  429        368  2024-05-01T00:00:00.000000000
3        1552  361        312  2022-01-20T00:00:00.000000000
4        7298  325        400  2022-10-12T00:00:00.000000000
..        ...  ...        ...                            ...
95       7115  118         14  2023-07-03T00:00:00.000000000
96       5935   78         39  2022-08-27T00:00:00.000000000
97       8440   21        447  2022-02-12T00:00:00.000000000
98       5561  298         37  2022-05-04T00:00:00.000000000
99       6533   26        445  2024-02-10T00:00:00.000000000

[100 rows x 4 columns]

Ejercicio: Utiliza un dataset de muestra que simule registros de temperaturas diarias durante un año. Realiza el siguiente análisis:

In [33]:
df_temp = pd.read_csv('C:/Users/franc/Documents/Proyectos/DataSets/city_temperature.csv')
df_temp

C:\Users\franc\AppData\Local\Temp\ipykernel_6332\1260999261.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_temp = pd.read_csv('C:/Users/franc/Documents/Proyectos/DataSets/city_temperature.csv')


Region  Country                   State                  City  \
0               Africa  Algeria                     NaN               Algiers   
1               Africa  Algeria                     NaN               Algiers   
2               Africa  Algeria                     NaN               Algiers   
3               Africa  Algeria                     NaN               Algiers   
4               Africa  Algeria                     NaN               Algiers   
...                ...      ...                     ...                   ...   
2906322  North America       US  Additional Territories  San Juan Puerto Rico   
2906323  North America       US  Additional Territories  San Juan Puerto Rico   
2906324  North America       US  Additional Territories  San Juan Puerto Rico   
2906325  North America       US  Additional Territories  San Juan Puerto Rico   
2906326  North America       US  Additional Territories  San Juan Puerto Rico   

         Month  Day  Year  AvgTemperature  
0            1    1  1995            64.2  
1            1    2  1995            49.4  
2            1    3  1995            48.8  
3            1    4  1995            46.4  
4            1    5  1995            47.9  
...        ...  ...   ...             ...  
2906322      7   27  2013            82.4  
2906323      7   28  2013            81.6  
2906324      7   29  2013            84.2  
2906325      7   30  2013            83.8  
2906326      7   31  2013            83.6  

[2906327 rows x 8 columns]

In [34]:
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2906327 entries, 0 to 2906326
Data columns (total 8 columns):
 #   Column          Dtype  
---  ------          -----  
 0   Region          object 
 1   Country         object 
 2   State           object 
 3   City            object 
 4   Month           int64  
 5   Day             int64  
 6   Year            int64  
 7   AvgTemperature  float64
dtypes: float64(1), int64(3), object(4)
memory usage: 177.4+ MB


In [35]:
# Calcula la temperatura máxima, mínima y media por mes.

month = df_temp['Month'] == 12
temp_per_month = df_temp[month]
np.min(temp_per_month['AvgTemperature'])

-99.0

In [36]:
np.max(temp_per_month['AvgTemperature'])

95.6

In [37]:
np.mean(temp_per_month['AvgTemperature'])

41.58702452575862

In [38]:
# Calcula la temperatura máxima, mínima y media por año.

year = df_temp['Year'] == 2013
temp_per_year = df_temp[year]
np.min(temp_per_year['AvgTemperature'])

-99.0

In [39]:
np.max(temp_per_year['AvgTemperature'])

109.4

In [40]:
np.mean(temp_per_year['AvgTemperature'])

58.942099242485654

In [41]:
main_temp = df_temp.groupby('Year')
main_temp['AvgTemperature'].mean()

Year
200    -99.000000
201    -99.000000
1995    50.788443
1996    50.433921
1997    51.531859
1998    50.157098
1999    52.386332
2000    52.388756
2001    54.882582
2002    52.598752
2003    53.516448
2004    54.664908
2005    56.302068
2006    56.337306
2007    57.640728
2008    56.853731
2009    58.334108
2010    57.902224
2011    58.848359
2012    60.218607
2013    58.942099
2014    58.488029
2015    60.639640
2016    60.781074
2017    60.952029
2018    59.804724
2019    59.211184
2020    53.775568
Name: AvgTemperature, dtype: float64

In [42]:
# Filtrar datos incoherentes

filter_temp = df_temp['Year'] >= 1900
df_t = df_temp[filter_temp]
mean_temp = df_t.groupby('Year')['AvgTemperature'].mean()

In [43]:
# Convertir esta tabla en arrays

years = np.array(mean_temp.index)
avg_temperatures = np.array(mean_temp.values)